server:
  port: 8080

spring:
  application:
    name: market
  profiles:
    active: default
  servlet:
  #multipart 파일처리 조건
    multipart:
      max-file-size: -1
      max-request-size: -1
  #database 접속정보
  datasource:
        #jdbc:mysql://앤드포인드/데이터베이스?옵션... rds    url: jdbc:mysql://mysql-1.cwpjd8suulvg.ap-northeast-2.rds.amazonaws.com/market?useUnicode=true&characterEncoding=utf-8
    username: admin
    password: password123!
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
  jpa:
    show-sql: true # 데이터처리할 때 SQL문을 보여줌
    generate-ddl: true # 클래스 정의에 따른 테이블 및 데이터베이스 객체 생성
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    host: ec2-13-125-229-154.ap-northeast-2.compute.amazonaws.com
    username: rabbitmq
    password: password123   
  eureka:
    client:
      service-url:
      # 유레카의 ec2 주소
      default-zone: http://ec2-3-36-141-39.ap-northeast-2.compute.amazonaws.com:8761/eureka/
    instance:
    # gateway의 ec2 주소
      hostname: ec2-3-36-141-39.ap-northeast-2.compute.amazonaws.com 
  