server:
  port: 8080

#

spring:
  application:
    name: market
  profiles:
    active: default
  servlet:
  #multipart 파일처리 조건
    multipart:
      max-file-size: -1
      max-request-size: -1
  #database 접속정보
  datasource:
        #jdbc:mysql://앤드포인드/데이터베이스?옵션... rds    url: jdbc:mysql://mysql-1.cwpjd8suulvg.ap-northeast-2.rds.amazonaws.com/market?useUnicode=true&characterEncoding=utf-8
    username: admin
    password: password123!
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
  jpa:
    show-sql: true # 데이터처리할 때 SQL문을 보여줌
    generate-ddl: true # 클래스 정의에 따른 테이블 및 데이터베이스 객체 생성
    properties:
      hibernate:
        jdbc:
          batch_size: 5
        order_inserts: true
        order_updates: true
        generate_statistics: true
  redis:
    host: 15.164.171.148
    port: 6379
    password: foobared
  rabbitmq:
    host: ec2-13-125-229-154.ap-northeast-2.compute.amazonaws.com
    username: rabbitmq
    password: password123   
  
eureka:
  client:
    service-url:
      # 유레카 서버 주소를 작성
      default-zone: http://192.168.0.31:8761/eureka/
  instance:
    # 클라이언트의 주소(자기 자신 서비스의 호스트명 ip addr, domain name)
    # AWS에서는 퍼블릭 IP를 안 쓰면 사설 IP대역으로 나옴.
    # 필수적으로 자신의 퍼블릭 ip주소나 도메인을 넣어줘야 함
    hostname: localhost


api:
  base-path: http://localhost:8080
---

spring:
  profiles: prod
  redis:
    host: 15.164.171.148
    port: 6379

eureka:
  client:
    service-url:
      # 유레카 서버의 주소를 작성
      # 유레카 설치된 ec2 ip 주소:8761/eureka/
      defaultZone: http://3.36.141.39:8761/eureka/
  instance:
      # 본인 서비스의 ec2 ip 주소
    hostname: 13.124.253.19
  
api:
  base-path: http://13.124.253.19:8080


# 클라이언트 부하 분산 활성화
ribbon:
  eureka:
    enabled: true