server:
  port: 8080

spring:
  servlet:
  #multipart 파일처리 조건
    multipart:
      max-file-size: -1
      max-request-size: -1
  #database 접속정보
  datasource:
        #jdbc:mysql://앤드포인드/데이터베이스?옵션... rds    url: jdbc:mysql://mysql-1.cwpjd8suulvg.ap-northeast-2.rds.amazonaws.com/market?useUnicode=true&characterEncoding=utf-8
    username: admin
    password: password123!
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
  jpa:
    show-sql: true # 데이터처리할 때 SQL문을 보여줌
    generate-ddl: true # 클래스 정의에 따른 테이블 및 데이터베이스 객체 생성
  rabbitmq:
    host: ec2-3-34-127-170.ap-northeast-2.compute.amazonaws.com
    username: rabbitmq
    password: password123    